### PR TITLE
Update tutorials.socially.angular2.step_18.md

### PR DESCRIPTION
**Pull request by bastienmoulia**
Replace `angular2-material` by `@angular/material` because of https://github.com/angular/material2/blob/master/CHANGELOG.md#200-alpha9-cobalt-kraken-2016-09-26

The step 19.4 and the title should also be changed.

### CODE REVIEW

**Comment by bastienmoulia** [comment]
The style for material design should now be include in the main.scss like in https://github.com/angular/material2/blob/master/docs/theming.md

``` scss
@import '{}/node_modules/@angular/material/core/theming/all-theme';
// Plus imports for other components in your app.

// Include the base styles for Angular Material core. We include this here so that you only
// have to load a single css file for Angular Material in your app.
@include md-core();

// Define the palettes for your theme using the Material Design palettes available in palette.scss
// (imported above). For each palette, you can optionally specify a default, lighter, and darker
// hue.
$candy-app-primary: md-palette($md-indigo);
$candy-app-accent:  md-palette($md-pink, A200, A100, A400);

// The warn palette is optional (defaults to red).
$candy-app-warn:    md-palette($md-red);

// Create the theme object (a Sass map containing all of the palettes).
$candy-app-theme: md-light-theme($candy-app-primary, $candy-app-accent, $candy-app-warn);

// Include theme styles for core and each component used in your app.
// Alternatively, you can import and @include the theme mixins for each component
// that you are using.
@include angular-material-theme($candy-app-theme);
```

**Comment by dotansimha** [comment]
Thanks @bastienmoulia, I am working on it right now, it requires more changes in the implementation of the Material Component, because there are some breaking changes.

**Comment by dotansimha** [comment]
@bastienmoulia I updated the usage to the latest version and updated the CSS and layout of the whole step with the latest Material. 
@Urigo will soon deploy the website and you will be able to see the changes.

**Comment by Urigo** [comment]
deployed

**Pull request closed without merging**
