### PR TITLE
Update tutorials.socially.angular1.step_04.md

### PR DESCRIPTION
**Pull request by cloverharvest**
Corrected missing step number, which changes '4.10' to '4.9'.  And then updated numbering for the tutorial#4 until step 4-20.

### CODE REVIEW

**Comment by Urigo** [comment]
@cloverharvest did you run it locally and made sure it makes it works?

**Comment by cloverharvest** [comment]
@Urigo  - socially app works up to the end of tutorial step 4. This includes party events displaying on view properly; and AddParty and RemoveParty passing all tests.

Aside:
I kept the autopublish in the package.
If I follow the prompt which says `meteor remove autopublish` during the testing section of the tutorial,  all the parties in my view disappear except the form.

**Comment by dotansimha** [comment]
@DAB0mB what do you think?

**Comment by DAB0mB** [comment]
@cloverharvest It doesn't seem like the steps and the tutorial are uncorrelated. Are you sure it's still relevant? About step 4.9 it's just that DiffBox doesn't support line removals so we'd rather writing instructions instead.

**Pull request closed without merging**
