### PR TITLE
Added app showcase to homepage

### PR DESCRIPTION
**Pull request by rachelmcgrane**

### CODE REVIEW

**Comment by simonv3** [comment]
@Urigo This looks great.

screenshot 2016-06-09 10 24 41

Todo: insert the form URL, and then I think this is ready for a merge.

**Comment by simonv3** [comment]
Awesome, @Urigo let us know what you think!

**Comment by Urigo** [comment]
yes!  thank you so much @rachelmcgrane (and @simonv3 )

**Comment by Urigo** [comment]
@rachelmcgrane could you change the "contact us" button to direct to a form similar to that but with less mandatory fields? and a general text field?
thanks

**Comment by rachelmcgrane** [comment]
@simonv3 set up the form, so he could modify it pretty easily I'm guessing

**Comment by Urigo** [comment]
I mean a second form, that will be linked from the contract us button, unrelated to that form

**Pull request merged**
